### ISSUE TITLE
[db-error] duplicate add

### ISSUE THREAD

**Issue by qdraw** [qdraw/starsky#1068]
**Describe the bug**

```
0|starsky  | info: app[0]
0|starsky  |       [SingleFile/db] info /2023/01/2023_01_08_d/20230108_101739_DSC08663_e.jpg : 2023-02-11 16:53:40

0|starsky  | info: app[0]
0|starsky  |       [AddItemAsync] catch-ed DbUpdateException going to retry 2 times /2023/01/2023_01_08_d/20230108_101739_DSC08663_e.jpg
0|starsky  |       Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException: The database operation was expected to affect 1 row(s), but actually affected 0 row(s); data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.
0|starsky  |          at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ThrowAggregateUpdateConcurrencyException(Int32 commandIndex, Int32 expectedRowsAffected, Int32 rowsAffected)
0|starsky  |          at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeResultSetWithoutPropagationAsync(Int32 commandIndex, RelationalDataReader reader, CancellationToken cancellationToken)
0|starsky  |          at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)
0|starsky  |          at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
0|starsky  |          at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
0|starsky  |          at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
0|starsky  |          at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
0|starsky  |          at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
0|starsky  |          at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
0|starsky  |          at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
0|starsky  |          at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.<>c__DisplayClass33_0`2.<<ExecuteAsync>b__0>d.MoveNext()
0|starsky  |       --- End of stack trace from previous location ---
0|starsky  |          at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
0|starsky  |          at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
0|starsky  |          at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
0|starsky  |          at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
0|starsky  |          at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
0|starsky  |          at starsky.foundation.database.Query.Query.<>c__DisplayClass27_0.<<AddItemAsync>g__LocalQuery|1>d.MoveNext() in /home/vsts/work/1/s/starsky/starsky.foundation.database/Query/Query.cs:line 624
0|starsky  |       --- End of stack trace from previous location ---
0|starsky  |          at starsky.foundation.database.Query.Query.AddItemAsync(FileIndexItem fileIndexItem) in /home/vsts/work/1/s/starsky/starsky.foundation.database/Query/Query.cs:line 635
0|starsky  | info: app[0]
0|starsky  |       [SyncWatcherConnector/Socket] /2023/01/2023_01_08_d/20230108_101739_DSC08663_e.jpg
0|starsky  | fail: app[0]
0|starsky  |       Error occurred executing task work item.
0|starsky  |       Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
0|starsky  |        ---> MySqlConnector.MySqlException (0x80004005): Duplicate entry '1124985' for key 'PRIMARY'
0|starsky  |          at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 44
0|starsky  |          at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 127
0|starsky  |          at MySqlConnector.MySqlDataReader.NextResultAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 87
0|starsky  |          at MySqlConnector.MySqlDataReader.DisposeAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 594
0|starsky  |          at MySqlConnector.MySqlDataReader.Close() in /_/src/MySqlConnector/MySqlDataReader.cs:line 333
0|starsky  |          at System.Data.Common.DbDataReader.CloseAsync()
0|starsky  |       --- End of stack trace from previous location ---
0|starsky  |          at Microsoft.EntityFrameworkCore.Storage.RelationalDataReader.DisposeAsync()
0|starsky  |          at Microsoft.EntityFrameworkCore.Storage.RelationalDataReader.DisposeAsync()
0|starsky  |          at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
0|starsky  |          --- End of inner exception stack trace ---
0|starsky  |          at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
0|starsky  |          at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
0|starsky  |          at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
0|starsky  |          at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
0|starsky  |          at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
0|starsky  |          at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
0|starsky  |          at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.<>c__DisplayClass33_0`2.<<ExecuteAsync>b__0>d.MoveNext()
0|starsky  |       --- End of stack trace from previous location ---
0|starsky  |          at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
0|starsky  |          at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
0|starsky  |          at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
0|starsky  |          at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
0|starsky  |          at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
0|starsky  |          at starsky.foundation.database.Notifications.NotificationQuery.AddNotification(String content) in /home/vsts/work/1/s/starsky/starsky.foundation.database/Notifications/NotificationQuery.cs:line 43
0|starsky  |          at starsky.foundation.sync.WatcherHelpers.SyncWatcherConnector.PushToSockets(List`1 filtered)
0|starsky  |          at starsky.foundation.sync.WatcherHelpers.SyncWatcherConnector.SyncTaskInternal(Tuple`3 watcherOutput) in /home/vsts/work/1/s/starsky/starsky.foundation.sync/WatcherHelpers/SyncWatcherConnector.cs:line 183
0|starsky  |          at starsky.foundation.sync.WatcherHelpers.QueueProcessor.<>c__DisplayClass5_0.<<QueueInput>b__0>d.MoveNext() in /home/vsts/work/1/s/starsky/starsky.foundation.sync/WatcherHelpers/QueueProcessor.cs:line 41
0|starsky  |       --- End of stack trace from previous location ---
0|starsky  |          at starsky.foundation.worker.Helpers.ProcessTaskQueue.ExecuteTask(Func`2 workItem, IWebLogger logger, IBaseBackgroundTaskQueue taskQueue, CancellationToken cancellationToken) in /home/vsts/work/1/s/starsky/starsky.foundation.worker/Helpers/ProcessTaskQueue.cs:line 88
0|starsky  | info: app[0]
0|starsky  |       [DiskWatcherBackgroundTaskQueue] next done & wait
0|starsky  | info: app[0]
0|starsky  |       [DiskWatcherBackgroundTaskQueue] next task: from:/mnt/data/sync/fotobieb/2023/01/2023_01_08_d/20230108_102603_DSC08669.arw
0|starsky  | info: app[0]
0|starsky  |       [SyncWatcherConnector] [/mnt/data/sync/fotobieb/2023/01/2023_01_08_d/20230108_102603_DSC08669.arw] - [] - [Changed]
0|starsky  | [Synchronize] Sync /2023/01/2023_01_08_d/20230108_102603_DSC08669.arw : 2023-02-11 16:54:00
0|starsky  | info: app[0]
0|starsky  |       [SingleFile/db] info /2023/01/2023_01_08_d/20230108_102603_DSC08669.arw : 2023-02-11 16:54:00
0|starsky  | info: app[0]
0|starsky  |       [RetrySaveChangesAsync] retry catch-ed exception from UpdateItemAsync InvalidOperationException
0|starsky  |       System.InvalidOperationException: The instance of entity type 'FileIndexItem' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.
0|starsky  |          at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.ThrowIdentityConflict(InternalEntityEntry entry)
0|starsky  |          at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry, Boolean updateDuplicate)
0|starsky  |          at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
0|starsky  |          at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges, Boolean modifyProperties)
0|starsky  |          at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode`1 node)
0|starsky  |          at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
0|starsky  |          at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.AttachGraph(InternalEntityEntry rootEntry, EntityState targetState, EntityState storeGeneratedWithKeySetTargetState, Boolean forceStateWhenUnknownKey)
0|starsky  |          at Microsoft.EntityFrameworkCore.DbContext.SetEntityState[TEntity](TEntity entity, EntityState entityState)
0|starsky  |          at starsky.foundation.database.Query.Query.<>c__DisplayClass17_0.<<UpdateItemAsync>g__LocalQuery|0>d.MoveNext() in /home/vsts/work/1/s/starsky/starsky.foundation.database/Query/Query.cs:line 268
0|starsky  |       --- End of stack trace from previous location ---
0|starsky  |          at starsky.foundation.database.Query.Query.UpdateItemAsync(FileIndexItem updateStatusContent) in /home/vsts/work/1/s/starsky/starsky.foundation.database/Query/Query.cs:line 284
0|starsky  | info: app[0]
0|starsky  |       [RetrySaveChangesAsync] next retry ~>
0|starsky  | info: app[0]
0|starsky  |       [SyncWatcherConnector/Socket] /2023/01/2023_01_08_d/20230108_102603_DSC08669.arw
0|starsky  | fail: app[0]
0|starsky  |       Error occurred executing task work item.
0|starsky  |       System.InvalidOperationException: Can't replace active reader.
0|starsky  |          at MySqlConnector.MySqlConnection.SetActiveReader(MySqlDataReader dataReader) in /_/src/MySqlConnector/MySqlConnection.cs:line 870
0|starsky  |          at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 451
0|starsky  |          at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 56
0|starsky  |          at MySqlConnector.MySqlCommand.ExecuteNonQueryAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 282
0|starsky  |          at MySqlConnector.MySqlConnection.BeginTransactionAsync(IsolationLevel isolationLevel, Nullable`1 isReadOnly, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 157
0|starsky  |          at MySqlConnector.MySqlConnection.BeginDbTransactionAsync(IsolationLevel isolationLevel, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 100
0|starsky  |          at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransactionAsync(IsolationLevel isolationLevel, CancellationToken cancellationToken)
0|starsky  |          at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransactionAsync(CancellationToken cancellationToken)
0|starsky  |          at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
0|starsky  |          at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
0|starsky  |          at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
0|starsky  |          at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
0|starsky  |          at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
0|starsky  |          at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.<>c__DisplayClass33_0`2.<<ExecuteAsync>b__0>d.MoveNext()
0|starsky  |       --- End of stack trace from previous location ---
0|starsky  |          at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
0|starsky  |          at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
0|starsky  |          at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
0|starsky  |          at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
0|starsky  |          at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
0|starsky  |          at starsky.foundation.database.Notifications.NotificationQuery.AddNotification(String content) in /home/vsts/work/1/s/starsky/starsky.foundation.database/Notifications/NotificationQuery.cs:line 43
0|starsky  |          at starsky.foundation.sync.WatcherHelpers.SyncWatcherConnector.PushToSockets(List`1 filtered)
0|starsky  |          at starsky.foundation.sync.WatcherHelpers.SyncWatcherConnector.SyncTaskInternal(Tuple`3 watcherOutput) in /home/vsts/work/1/s/starsky/starsky.foundation.sync/WatcherHelpers/SyncWatcherConnector.cs:line 183
0|starsky  |          at starsky.foundation.sync.WatcherHelpers.QueueProcessor.<>c__DisplayClass5_0.<<QueueInput>b__0>d.MoveNext() in /home/vsts/work/1/s/starsky/starsky.foundation.sync/WatcherHelpers/QueueProcessor.cs:line 41
0|starsky  |       --- End of stack trace from previous location ---
0|starsky  |          at starsky.foundation.worker.Helpers.ProcessTaskQueue.ExecuteTask(Func`2 workItem, IWebLogger logger, IBaseBackgroundTaskQueue taskQueue, CancellationToken cancellationToken) in /home/vsts/work/1/s/starsky/starsky.foundation.worker/Helpers/ProcessTaskQueue.cs:line 88
```

```
0|starsky  | fail: app[0]
0|starsky  |       Error occurred executing task work item.
0|starsky  |       System.InvalidOperationException: The instance of entity type 'FileIndexItem' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.
0|starsky  |          at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.ThrowIdentityConflict(InternalEntityEntry entry)
0|starsky  |          at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry, Boolean updateDuplicate)
0|starsky  |          at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.KeyPropertyChanged(InternalEntityEntry entry, IProperty property, IEnumerable`1 containingPrincipalKeys, IEnumerable`1 containingForeignKeys, Object oldValue, Object newValue)
0|starsky  |          at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.LocalDetectChanges(InternalEntityEntry entry)
0|starsky  |          at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectChanges(IStateManager stateManager)
0|starsky  |          at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
0|starsky  |          at starsky.foundation.database.Notifications.NotificationQuery.AddNotification(String content) in /home/vsts/work/1/s/starsky/starsky.foundation.database/Notifications/NotificationQuery.cs:line 43
0|starsky  |          at starsky.foundation.sync.WatcherHelpers.SyncWatcherConnector.PushToSockets(List`1 filtered)
0|starsky  |          at starsky.foundation.sync.WatcherHelpers.SyncWatcherConnector.SyncTaskInternal(Tuple`3 watcherOutput) in /home/vsts/work/1/s/starsky/starsky.foundation.sync/WatcherHelpers/SyncWatcherConnector.cs:line 183
0|starsky  |          at starsky.foundation.sync.WatcherHelpers.QueueProcessor.<>c__DisplayClass5_0.<<QueueInput>b__0>d.MoveNext() in /home/vsts/work/1/s/starsky/starsky.foundation.sync/WatcherHelpers/QueueProcessor.cs:line 41
0|starsky  |       --- End of stack trace from previous location ---
0|starsky  |          at starsky.foundation.worker.Helpers.ProcessTaskQueue.ExecuteTask(Func`2 workItem, IWebLogger logger, IBaseBackgroundTaskQueue taskQueue, CancellationToken cancellationToken) in /home/vsts/work/1/s/starsky/starsky.foundation.worker/Helpers/ProcessTaskQueue.cs:line 88
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by qdraw** [comment]
not able to reproducte
