### ISSUE TITLE
Flaky unit tests (StarskyCliTest_StarskyCliSubPathOneImage)

### ISSUE THREAD

**Issue by qdraw** [qdraw/starsky#325]
**Describe the bug**

```
========================================
TestNetCore
========================================
Testing project /home/runner/work/starsky/starsky/starsky/starskytest/starskytest.csproj
Test run for /home/runner/work/starsky/starsky/starsky/starskytest/bin/Release/netcoreapp3.1/starskytest.dll(.NETCoreApp,Version=v3.1)
Starting test execution, please wait...

A total of 1 test files matched the specified pattern.
[PNG-IHDR] Image Width = 512
  X StarskyCliTest_StarskyCliSubPathOneImage [122ms]
  Error Message:
   Test method starskytest.starskySyncCli.StarskyCliTest.StarskyCliTest_StarskyCliSubPathOneImage threw exception: 
System.ArgumentException: An item with the same key has already been added. Key: 25
  Stack Trace:
      at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Microsoft.EntityFrameworkCore.InMemory.Storage.Internal.InMemoryTable`1.Create(IUpdateEntry entry)
   at Microsoft.EntityFrameworkCore.InMemory.Storage.Internal.InMemoryStore.ExecuteTransaction(IList`1 entries, IDiagnosticsLogger`1 updateLogger)
   at Microsoft.EntityFrameworkCore.InMemory.Storage.Internal.InMemoryDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.Storage.Internal.NoopExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at starsky.foundation.database.Query.Query.AddItem(FileIndexItem updateStatusContent) in /home/runner/work/starsky/starsky/starsky/starsky.foundation.database/Query/Query.cs:line 550
   at starskycore.Services.SyncService.AddFoldersToDatabase(List`1 localSubFolderDbStyle, List`1 databaseSubFolderList) in /home/runner/work/starsky/starsky/starsky/starskycore/Services/SyncServiceAddFoldersToDatabase.cs:line 39
   at starskycore.Services.SyncService.SyncFiles(String subPath, Boolean recursive) in /home/runner/work/starsky/starsky/starsky/starskycore/Services/SyncService.cs:line 80
   at starskycore.Services.SyncServiceCli.Sync(String[] args, ISync syncService, AppSettings appSettings, IConsole console, IThumbnailCleaner thumbnailCleaner, ISelectorStorage selectorStorage) in /home/runner/work/starsky/starsky/starsky/starskycore/Services/SyncServiceCli.cs:line 43
   at starskysynccli.Program.Main(String[] args) in /home/runner/work/starsky/starsky/starsky/starskysynccli/Program.cs:line 40
```
https://github.com/qdraw/starsky/runs/2125690631

**Comment by qdraw** [comment]
should be fixed in: c5432dbae407ece1b8d1d3b390889d0f9be28596
