### ISSUE TITLE
Websocket exception

### ISSUE THREAD

**Issue by qdraw** [qdraw/starsky#436]
see: https://github.com/qdraw/starsky/issues/440
```
0|starsky  | System.Net.WebSockets.WebSocketException (0x80004005): The WebSocket is in an invalid state ('Closed') for this operation. Valid states are: 'Open, CloseReceived'
0|starsky  |    at System.Net.WebSockets.WebSocketValidate.ThrowIfInvalidState(WebSocketState currentState, Boolean isDisposed, WebSocketState[] validStates)
0|starsky  |    at System.Net.WebSockets.ManagedWebSocket.SendPrivateAsync(ReadOnlyMemory`1 buffer, WebSocketMessageType messageType, Boolean endOfMessage, CancellationToken cancellationToken)
0|starsky  | --- End of stack trace from previous location where exception was thrown ---
0|starsky  |    at starsky.foundation.sync.WatcherHelpers.SyncWatcherConnector.Sync(Tuple`3 watcherOutput) in /home/vsts/work/1/s/starsky/starsky.foundation.sync/WatcherHelpers/SyncWatcherConnector.cs:line 71
0|starsky  |    at starsky.foundation.sync.WatcherHelpers.FileProcessor.EndlessWorkQueueAsync(CancellationToken token) in /home/vsts/work/1/s/starsky/starsky.foundation.sync/WatcherHelpers/FileProcessor.cs:line 72
0|starsky  |    at starsky.foundation.sync.WatcherHelpers.FileProcessor.EndlessWorkQueue() in /home/vsts/work/1/s/starsky/starsky.foundation.sync/WatcherHelpers/FileProcessor.cs:line 59
0|starsky  |    at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
0|starsky  |    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
0|starsky  | --- End of stack trace from previous location where exception was thrown ---
0|starsky  |    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
0|starsky  |    at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by qdraw** [comment]
duplicate of https://github.com/qdraw/starsky/issues/440
