### ISSUE TITLE
starskywebftpcli -p Not logged in ?

### ISSUE THREAD

**Issue by qdraw** [qdraw/starsky#629]
**Describe the bug**

```

starskywebftpcli -p
,,,,..................Unhandled exception. System.Net.WebException: The remote server returned an error: (530) Not logged in.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Net.FtpWebRequest.SyncRequestCallback(Object obj)
   at System.Net.CommandStream.InvokeRequestCallback(Object obj)
   at System.Net.CommandStream.Abort(Exception e)
   at System.Net.FtpWebRequest.FinishRequestStage(RequestStage stage)
   at System.Net.FtpWebRequest.GetRequestStream()
   at starsky.feature.webftppublish.FtpAbstractions.Helpers.WrapFtpWebRequest.GetRequestStream() in /home/vsts/work/1/s/starsky/starsky.feature.webftppublish/FtpAbstractions/Helpers/WrapFtpWebRequest.cs:line 71
   at starsky.feature.webftppublish.Services.FtpService.Upload(String parentDirectory, String subPath, String toFtpPath) in /home/vsts/work/1/s/starsky/starsky.feature.webftppublish/Services/FtpService.cs:line 185
   at starsky.feature.webftppublish.Services.FtpService.MakeUpload(String parentDirectory, String slug, IEnumerable`1 copyThisFilesSubPaths) in /home/vsts/work/1/s/starsky/starsky.feature.webftppublish/Services/FtpService.cs:line 161
   at starsky.feature.webftppublish.Services.FtpService.Run(String parentDirectory, String slug, Dictionary`2 copyContent) in /home/vsts/work/1/s/starsky/starsky.feature.webftppublish/Services/FtpService.cs:line 85
   at starsky.feature.webftppublish.Helpers.WebFtpCli.Run(String[] args) in /home/vsts/work/1/s/starsky/starsky.feature.webftppublish/Helpers/WebFtpCli.cs:line 82
   at starskywebftpcli.Program.Main(String[] args) in /home/vsts/work/1/s/starsky/starskywebftpcli/Program.cs:line 34
   at starskywebftpcli.Program.<Main>(String[] args)
Aborted
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by qdraw** [comment]
https://github.com/qdraw/starsky/pull/635
