### ISSUE TITLE
OutOfMemoryException on telemetry

### ISSUE THREAD

**Issue by qdraw** [qdraw/starsky#660]
**Describe the bug**
```
Unhandled exception. System.Threading.Tasks.TaskSchedulerException: An exception was thrown by a TaskScheduler.
 ---> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Threading.Thread.StartInternal(ThreadHandle t, Int32 stackSize, Int32 priority, Char* pThreadName)
   at System.Threading.Thread.StartCore()
   at System.Threading.Tasks.Task.ScheduleAndStart(Boolean needsProtection)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ScheduleAndStart(Boolean needsProtection)
   at Microsoft.ApplicationInsights.Channel.InMemoryTransmitter..ctor(TelemetryBuffer buffer)
   at Microsoft.ApplicationInsights.Channel.InMemoryChannel..ctor()
   at Microsoft.ApplicationInsights.Extensibility.TelemetrySink..ctor(TelemetryConfiguration telemetryConfiguration, ITelemetryChannel telemetryChannel)
   at Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration..ctor(String instrumentationKey, ITelemetryChannel channel)
   at Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration.CreateDefault()
   at starsky.foundation.databasetelemetry.Helpers.TelemetryConfigurationHelper.CreateTelemetryConfiguration(String appInsightsInstrumentationKey) in /home/vsts/work/1/s/starsky/starsky.foundation.databasetelemetry/Helpers/TelemetryConfigurationHelper.cs:line 34
   at starsky.foundation.databasetelemetry.Helpers.TelemetryConfigurationHelper.InitTelemetryClient(String appInsightsConnectionString, String roleName) in /home/vsts/work/1/s/starsky/starsky.foundation.databasetelemetry/Helpers/TelemetryConfigurationHelper.cs:line 19
   at starsky.foundation.database.Helpers.SetupDatabaseTypes.EnableDatabaseTracking(DbContextOptionsBuilder`1 databaseOptionsBuilder) in /home/vsts/work/1/s/starsky/starsky.foundation.database/Helpers/SetupDatebaseTypes.cs:line 104
   at starsky.foundation.database.Helpers.SetupDatabaseTypes.BuilderDbFactorySwitch(String foundationDatabaseName) in /home/vsts/work/1/s/starsky/starsky.foundation.database/Helpers/SetupDatebaseTypes.cs:line 81
   at starsky.foundation.database.Helpers.SetupDatabaseTypes.BuilderDbFactory() in /home/vsts/work/1/s/starsky/starsky.foundation.database/Helpers/SetupDatebaseTypes.cs:line 30
   at starsky.foundation.database.Query.QueryFactory.Query() in /home/vsts/work/1/s/starsky/starsky.foundation.database/Query/QueryFactory.cs:line 41
   at starsky.foundation.sync.SyncServices.SyncFolder.<>c__DisplayClass10_0.<<LoopOverFolder>b__1>d.MoveNext() in /home/vsts/work/1/s/starsky/starsky.foundation.sync/SyncServices/SyncFolder.cs:line 115
--- End of stack trace from previous location ---
   at starsky.foundation.platform.Extensions.EnumerableExtensions.ForEachAsync[TSource,TResult](IEnumerable`1 items, Func`2 action, Int32 maxDegreesOfParallelism) in /home/vsts/work/1/s/starsky/starsky.foundation.platform/Extensions/EnumerableExtensions.cs:line 40
   at starsky.foundation.sync.SyncServices.SyncFolder.LoopOverFolder(IReadOnlyCollection`1 fileIndexItems, IReadOnlyCollection`1 pathsOnDisk, SocketUpdateDelegate updateDelegate) in /home/vsts/work/1/s/starsky/starsky.foundation.sync/SyncServices/SyncFolder.cs:line 117
   at starsky.foundation.sync.SyncServices.SyncFolder.Folder(String inputSubPath, SocketUpdateDelegate updateDelegate) in /home/vsts/work/1/s/starsky/starsky.foundation.sync/SyncServices/SyncFolder.cs:line 61
   at starsky.foundation.sync.SyncServices.Synchronize.Sync(String subPath, Boolean recursive, SocketUpdateDelegate updateDelegate) in /home/vsts/work/1/s/starsky/starsky.foundation.sync/SyncServices/Synchronize.cs:line 57
   at starsky.foundation.sync.Helpers.SyncCli.Sync(String[] args) in /home/vsts/work/1/s/starsky/starsky.foundation.sync/Helpers/SyncCli.cs:line 54
   at starskysynchronizecli.Program.Main(String[] args) in /home/vsts/work/1/s/starsky/starskysynchronizecli/Program.cs:line 45
   at starskysynchronizecli.Program.<Main>(String[] args)
/opt/starsky/starskysynccli_recentyears.sh: line 27: 21183 Aborted                 /opt/starsky/starsky/starskysynchronizecli
script ended
Lockfile removed
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by qdraw** [comment]
- [x]   (Fixed) _Back-end_ System.OutOfMemoryException trigger Garbage collection (PR #661 / Issue #660)
