### ISSUE TITLE
Geo data already exists exception

### ISSUE THREAD

**Issue by qdraw** [qdraw/starsky#772]
https://github.com/qdraw/starsky/actions/runs/2365748263
```

43 [linux/amd64->arm64 build-env 9/9] RUN if [ "" != "" ]; then         chmod +x docker_demo_setup.sh ;        ./docker_demo_setup.sh ;    else         GEO_CLI_PATH="/app/starskygeocli/starskygeocli.csproj" ;        TEMP_FOLDER="/app/out/temp" ;        mkdir -p $TEMP_FOLDER ;        dotnet run --project $GEO_CLI_PATH --configuration Release -- --tempfolder $TEMP_FOLDER -h -v ;    fi
[1089](https://github.com/qdraw/starsky/runs/6542328575?check_suite_focus=true#step:5:1091)
#43 CANCELED
[1090](https://github.com/qdraw/starsky/runs/6542328575?check_suite_focus=true#step:5:1092)
------
[1091](https://github.com/qdraw/starsky/runs/6542328575?check_suite_focus=true#step:5:1093)
 > [linux/amd64 build-env 9/9] RUN if [ "" != "" ]; then         chmod +x docker_demo_setup.sh ;        ./docker_demo_setup.sh ;    else         GEO_CLI_PATH="/app/starskygeocli/starskygeocli.csproj" ;        TEMP_FOLDER="/app/out/temp" ;        mkdir -p $TEMP_FOLDER ;        dotnet run --project $GEO_CLI_PATH --configuration Release -- --tempfolder $TEMP_FOLDER -h -v ;    fi:
[1092](https://github.com/qdraw/starsky/runs/6542328575?check_suite_focus=true#step:5:1094)
#45 85.09    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
[1093](https://github.com/qdraw/starsky/runs/6542328575?check_suite_focus=true#step:5:1095)
#45 85.09    at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
[1094](https://github.com/qdraw/starsky/runs/6542328575?check_suite_focus=true#step:5:1096)
#45 85.09    at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
[1095](https://github.com/qdraw/starsky/runs/6542328575?check_suite_focus=true#step:5:1097)
#45 85.09    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
[1096](https://github.com/qdraw/starsky/runs/6542328575?check_suite_focus=true#step:5:1098)
#45 85.09    at System.IO.Compression.ZipFileExtensions.ExtractToFile(ZipArchiveEntry source, String destinationFileName, Boolean overwrite)
[1097](https://github.com/qdraw/starsky/runs/6542328575?check_suite_focus=true#step:5:1099)
#45 85.09    at starsky.foundation.storage.ArchiveFormats.Zipper.ExtractZip(String zipInputFullPath, String storeZipFolderFullPath) in /app/starsky.foundation.storage/ArchiveFormats/Zipper.cs:line 37
[1098](https://github.com/qdraw/starsky/runs/6542328575?check_suite_focus=true#step:5:1100)
#45 85.09    at starsky.feature.geolookup.Services.GeoFileDownload.Download() in /app/starsky.feature.geolookup/Services/GeoFileDownload.cs:line 45
[1099](https://github.com/qdraw/starsky/runs/6542328575?check_suite_focus=true#step:5:1101)
#45 85.09    at starsky.feature.geolookup.Services.GeoCli.CommandLineAsync(String[] args) in /app/starsky.feature.geolookup/Services/GeoCli.cs:line 63
[1100](https://github.com/qdraw/starsky/runs/6542328575?check_suite_focus=true#step:5:1102)
#45 85.09    at starskyGeoCli.Program.Main(String[] args) in /app/starskygeocli/Program.cs:line 50
[1101](https://github.com/qdraw/starsky/runs/6542328575?check_suite_focus=true#step:5:1103)
#45 85.09    at starskyGeoCli.Program.<Main>(String[] args)
[1102](https://github.com/qdraw/starsky/runs/6542328575?check_suite_focus=true#step:5:1104)
------
[1103](https://github.com/qdraw/starsky/runs/6542328575?check_suite_focus=true#step:5:1105)
Dockerfile:70
[1104](https://github.com/qdraw/starsky/runs/6542328575?check_suite_focus=true#step:5:1106)
--------------------
[1105](https://github.com/qdraw/starsky/runs/6542328575?check_suite_focus=true#step:5:1107)
  69 |     
[1106](https://github.com/qdraw/starsky/runs/6542328575?check_suite_focus=true#step:5:1108)
  70 | >>> RUN if [ "$ISDEMO" != "" ]; then \
[1107](https://github.com/qdraw/starsky/runs/6542328575?check_suite_focus=true#step:5:1109)
  71 | >>>         chmod +x docker_demo_setup.sh ;\
[1108](https://github.com/qdraw/starsky/runs/6542328575?check_suite_focus=true#step:5:1110)
  72 | >>>         ./docker_demo_setup.sh ;\
[1109](https://github.com/qdraw/starsky/runs/6542328575?check_suite_focus=true#step:5:1111)
  73 | >>>     else \
[1110](https://github.com/qdraw/starsky/runs/6542328575?check_suite_focus=true#step:5:1112)
  74 | >>>         # it should cache faster
[1111](https://github.com/qdraw/starsky/runs/6542328575?check_suite_focus=true#step:5:1113)
  75 | >>>         GEO_CLI_PATH="/app/starskygeocli/starskygeocli.csproj" ;\
[1112](https://github.com/qdraw/starsky/runs/6542328575?check_suite_focus=true#step:5:1114)
  76 | >>>         TEMP_FOLDER="/app/out/temp" ;\
[1113](https://github.com/qdraw/starsky/runs/6542328575?check_suite_focus=true#step:5:1115)
  77 | >>>         mkdir -p $TEMP_FOLDER ;\
[1114](https://github.com/qdraw/starsky/runs/6542328575?check_suite_focus=true#step:5:1116)
  78 | >>>         dotnet run --project $GEO_CLI_PATH --configuration Release -- --tempfolder $TEMP_FOLDER -h -v ;\
[1115](https://github.com/qdraw/starsky/runs/6542328575?check_suite_focus=true#step:5:1117)
  79 | >>>     fi
[1116](https://github.com/qdraw/starsky/runs/6542328575?check_suite_focus=true#step:5:1118)
  80 |     
[1117](https://github.com/qdraw/starsky/runs/6542328575?check_suite_focus=true#step:5:1119)
--------------------
[1118](https://github.com/qdraw/starsky/runs/6542328575?check_suite_focus=true#step:5:1120)
error: failed to solve: process "/bin/sh -c if [ \"$ISDEMO\" != \"\" ]; then         chmod +x docker_demo_setup.sh ;        ./docker_demo_setup.sh ;    else         GEO_CLI_PATH=\"/app/starskygeocli/starskygeocli.csproj\" ;        TEMP_FOLDER=\"/app/out/temp\" ;        mkdir -p $TEMP_FOLDER ;        dotnet run --project $GEO_CLI_PATH --configuration Release -- --tempfolder $TEMP_FOLDER -h -v ;    fi" did not complete successfully: exit code: 134
[1119](https://github.com/qdraw/starsky/runs/6542328575?check_suite_focus=true#step:5:1121)
Error: buildx failed with: error: failed to solve: process "/bin/sh -c if [ \"$ISDEMO\" != \"\" ]; then         chmod +x docker_demo_setup.sh ;        ./docker_demo_setup.sh ;    else         GEO_CLI_PATH=\"/app/starskygeocli/starskygeocli.csproj\" ;        TEMP_FOLDER=\"/app/out/temp\" ;        mkdir -p $TEMP_FOLDER ;        dotnet run --project $GEO_CLI_PATH --configuration Release -- --tempfolder $TEMP_FOLDER -h -v ;    fi" did not complete successfully: exit code: 134
```

**Comment by qdraw** [comment]
fixed 24/6 with overwrite
