### ISSUE TITLE
Mysql database exception

### ISSUE THREAD

**Issue by qdraw** [qdraw/starsky#851]
**Describe the bug**
```

0|starsky  |       [UpdateWriteDiskDatabase] ExifTool result: -json -overwrite_original "-xmp:Label"="Winner" -ColorClass="1" -Prefs="Tagged:0 ColorClass:1 Rating:0 FrameNum:0"  path:/2022/07/2022_07_30/20220730_133440_DSC08032_e.jpg
0|starsky  | info: app[0]
0|starsky  |       [RetrySaveChangesAsync] retry catch-ed exception from UpdateItemAsync InvalidOperationException
0|starsky  |       System.InvalidOperationException: The instance of entity type 'FileIndexItem' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.
0|starsky  |          at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.ThrowIdentityConflict(InternalEntityEntry entry)
0|starsky  |          at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry, Boolean updateDuplicate)
0|starsky  |          at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.KeyPropertyChanged(InternalEntityEntry entry, IProperty property, IEnumerable`1 containingPrincipalKeys, IEnumerable`1 containingForeignKeys, Object oldValue, Object newValue)
0|starsky  |          at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.LocalDetectChanges(InternalEntityEntry entry)
0|starsky  |          at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectChanges(IStateManager stateManager)
0|starsky  |          at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
0|starsky  |          at starsky.foundation.database.Query.Query.<>c__DisplayClass17_0.<<UpdateItemAsync>g__LocalQuery|0>d.MoveNext() in /home/vsts/work/1/s/starsky/starsky.foundation.database/Query/Query.cs:line 271
0|starsky  |       --- End of stack trace from previous location ---
0|starsky  |          at starsky.foundation.database.Query.Query.UpdateItemAsync(FileIndexItem updateStatusContent) in /home/vsts/work/1/s/starsky/starsky.foundation.database/Query/Query.cs:line 276
0|starsky  | info: app[0]
0|starsky  |       [RetrySaveChangesAsync] next retry ~>
0|starsky  | fail: app[0]
0|starsky  |       Error occurred executing workItem
0|starsky  |       System.InvalidOperationException: Can't replace active reader.
0|starsky  |          at MySqlConnector.MySqlConnection.SetActiveReader(MySqlDataReader dataReader) in /_/src/MySqlConnector/MySqlConnection.cs:line 870
0|starsky  |          at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 451
0|starsky  |          at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 56
0|starsky  |          at MySqlConnector.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 330
0|starsky  |          at MySqlConnector.MySqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 323
0|starsky  |          at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
0|starsky  |          at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
0|starsky  |          at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
0|starsky  |          at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.<>c__DisplayClass33_0`2.<<ExecuteAsync>b__0>d.MoveNext()
0|starsky  |       --- End of stack trace from previous location ---
0|starsky  |          at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
0|starsky  |          at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
0|starsky  |          at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
0|starsky  |          at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
0|starsky  |          at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
0|starsky  |          at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
0|starsky  |          at starsky.foundation.database.Query.Query.<>c__DisplayClass31_0.<<GetParentItems>g__LocalQuery|0>d.MoveNext() in /home/vsts/work/1/s/starsky/starsky.foundation.database/Query/Query.cs:line 776
0|starsky  |       --- End of stack trace from previous location ---
0|starsky  |          at starsky.foundation.database.Query.Query.GetParentItems(List`1 pathListShouldExist) in /home/vsts/work/1/s/starsky/starsky.foundation.database/Query/Query.cs:line 782
0|starsky  |          at starsky.foundation.database.Query.Query.AddParentItemsAsync(String subPath) in /home/vsts/work/1/s/starsky/starsky.foundation.database/Query/Query.cs:line 808
0|starsky  |          at starsky.foundation.sync.SyncServices.SyncSingleFile.UpdateItem(FileIndexItem dbItem, Int64 size, String subPath)
0|starsky  |          at starsky.foundation.sync.SyncServices.SyncSingleFile.SingleFile(String subPath, SocketUpdateDelegate updateDelegate) in /home/vsts/work/1/s/starsky/starsky.foundation.sync/SyncServices/SyncSingleFile.cs:line 134
0|starsky  |          at starsky.foundation.sync.SyncServices.Synchronize.Sync(String subPath, Boolean recursive, SocketUpdateDelegate updateDelegate) in /home/vsts/work/1/s/starsky/starsky.foundation.sync/SyncServices/Synchronize.cs:line 60
0|starsky  |          at starsky.foundation.sync.WatcherHelpers.SyncWatcherConnector.SyncTaskInternal(Tuple`3 watcherOutput) in /home/vsts/work/1/s/starsky/starsky.foundation.sync/WatcherHelpers/SyncWatcherConnector.cs:line 162
0|starsky  |          at starsky.foundation.sync.WatcherHelpers.QueueProcessor.<>c__DisplayClass8_0.<<QueueInput>b__0>d.MoveNext() in /home/vsts/work/1/s/starsky/starsky.foundation.sync/WatcherHelpers/QueueProcessor.cs:line 59
0|starsky  |       --- End of stack trace from previous location ---
0|starsky  |          at starsky.foundation.worker.Helpers.ProcessTaskQueue.ProcessTaskQueueAsync(IBaseBackgroundTaskQueue taskQueue, IWebLogger logger, CancellationToken stoppingToken) in /home/vsts/work/1/s/starsky/starsky.foundation.worker/Helpers/ProcessTaskQueue.cs:line 20
0|starsky  | info: app[0]
0|starsky  |       write /2022/07/2022_07_30/20220730_134142_DSC08044_e2.jpg is True
0|starsky  | info: app[0]
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by qdraw** [comment]
unable to reproduce
