### ISSUE TITLE
GeoCLI refactor

### ISSUE THREAD

**Issue by qdraw** [qdraw/starsky#907]
**Describe the bug**
```
20:29:18 [DBG] info: app[0]
20:29:18 [DBG]       [Download] HttpClientHelper > download.geonames.org ~ https://download.geonames.org/export/dump/cities1000.zip
20:29:18 [DBG] fail: app[0]
20:29:18 [DBG]       catch-ed GeoFileDownload GeoReverseLookup error
20:29:18 [DBG]       System.IO.FileNotFoundException: Could not find file '/home/runner/work/***/***/***/generic-netcore/dependencies/cities1000.txt'.
20:29:18 [DBG]       File name: '/home/runner/work/***/***/***/generic-netcore/dependencies/cities1000.txt'
20:29:18 [DBG]          at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
20:29:18 [DBG]          at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
20:29:18 [DBG]          at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
20:29:18 [DBG]          at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
20:29:18 [DBG]          at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
20:29:18 [DBG]          at System.IO.File.OpenRead(String path)
20:29:18 [DBG]          at NGeoNames.GeoFileReader.GetStream(String path, FileType filetype)
20:29:18 [DBG]          at NGeoNames.GeoFileReader.ReadRecords[T](String path, FileType filetype, IParser`1 parser)+MoveNext()
20:29:18 [DBG]          at NGeoNames.ReverseGeoCode`1.AddRange(IEnumerable`1 nodes)
20:29:18 [DBG]          at NGeoNames.ReverseGeoCode`1..ctor(IEnumerable`1 nodes)
20:29:18 [DBG]          at ***.feature.geolookup.Services.GeoReverseLookup.InitReverseGeoCode() in /home/runner/work/***/***/***/***.feature.geolookup/Services/GeoReverseLookup.cs:line 59
20:29:18 [DBG] info: app[0]
20:29:18 [DBG]       [ReadString] HttpClientHelper > exiftool.org ~ https://exiftool.org/checksums.txt
20:29:18 [DBG] info: app[0]
20:29:18 [DBG]       [Download] HttpClientHelper > exiftool.org ~ https://exiftool.org/Image-ExifTool-12.47.tar.gz
20:29:19 [DBG] info: app[0]
20:29:19 [DBG]       [DownloadForUnix] ExifTool downloaded: /home/runner/work/***/***/***/generic-netcore/dependencies/exiftool-unix/exiftool
20:29:19 [DBG] info: app[0]
20:29:19 [DBG]       [Download] HttpClientHelper > download.geonames.org ~ https://download.geonames.org/export/dump/cities1000.zip
20:29:19 [DBG] info: app[0]
20:29:19 [DBG]       [Download] HttpClientHelper > download.geonames.org ~ https://download.geonames.org/export/dump/admin1CodesASCII.txt
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by qdraw** [comment]
fixed in #923
